# TODO

- EDA (correlation matrix) ; fouskakis 
- Feature extraction
- try classifiers 
- grid search -> find best 
- further research -> kaggle notebooks

# Imports

In [24]:
import pandas as pd
import numpy as np
from ucimlrepo import fetch_ucirepo 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression

In [25]:
path = 'Data/'
RAND_STATE = 42

In [26]:
inputs = pd.read_csv(path + 'diabetes_012_health_indicators_BRFSS2015.csv')
df = inputs.copy()

# Preprocessing

In [27]:
df.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [28]:
df.isnull().sum().sum()

0

In [29]:
for col in df.columns:
    df[col] = df[col].astype(int)


In [30]:
labels = df[['Diabetes_012']].to_numpy().flatten()
labels

array([0, 0, 0, ..., 0, 0, 2])

0: Υγιείς
1: Προδιαβητικοί
2: Διαβητικοί

In [41]:
_ , class_samples = np.unique(labels, return_counts=True)
class_freq = class_samples/sum(class_samples)
class_freq

array([0.8424117 , 0.01825528, 0.13933302])

In [32]:
len(df[df['Diabetes_012']==0]),  len(df[df['Diabetes_012']==1]), len(df[df['Diabetes_012']==2])

(213703, 4631, 35346)

In [33]:
# df = df.drop(['Diabetes_012'], axis=1)

# Random Forest Classifier

In [35]:
train_data, test_data, train_labels, test_labels = train_test_split(df, labels, 
                                                                    test_size = 0.25,
                                                                    random_state = RAND_STATE,
                                                                    stratify=labels)
# Stratify = y creates train and test data in a way that every label is represented with the same percentage on both train and test subsets


In [36]:
rf = RandomForestClassifier(random_state=RAND_STATE,
                                       class_weight='balanced')

In [37]:
rf.fit(train_data, train_labels)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [38]:
rf.score(test_data, test_labels)

0.8380952380952381

In [39]:
# print(f'train labels classes:{np.unique(train_labels, return_counts=True)}')
# print(f'test labels classes:{np.unique(test_labels, return_counts=True)}')
_ , class_samples = np.unique(train_labels, return_counts=True)
class_samples/sum(class_samples)

array([0.84241039, 0.01825397, 0.13933565])

In [40]:
print(classification_report(test_labels, rf.predict(test_data)))

              precision    recall  f1-score   support

           0       0.86      0.97      0.91     53426
           1       0.00      0.00      0.00      1158
           2       0.46      0.16      0.23      8836

    accuracy                           0.84     63420
   macro avg       0.44      0.38      0.38     63420
weighted avg       0.79      0.84      0.80     63420



In [ ]:
test_labels

# Logistic Regression

# Resample

In [43]:
T = 0.5
sampling_probs = np.exp((1-class_freq)/T) / np.sum(np.exp((1-class_freq)/T)) 
sampling_probs

array([0.09729095, 0.50573802, 0.39697103])

In [ ]:
new_df = df.sample()